package oracle.model;

// Generated 2016-1-13 13:56:34 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.huatek.frame.core.model.BaseEntity;

/**
 * ExceptionLog generated by hbm2java
 */
@Entity
@Table(name = "EXCEPTION_LOG", schema = "")
public class ExceptionLog extends BaseEntity {
	
	/**
	 */
	@Id
	@Column(name = "ECPT_ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "my_seq", sequenceName = "S_ECPT_ID")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "my_seq")
	private Long id;
	
	/**
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ECPT_ACCT_ID", nullable = false)
	private FwAccount fwAccount;
	
	/**
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ECPT_ACTI_ID", nullable = false)
	private FwSource fwSource;
	
	/**
	 */
	@Column(name = "ECPT_MODULE", nullable = false, length = 30)
	private String ecptModule;
	
	/**
	 */
	@Column(name = "ECPT_CODE", nullable = false, length = 10)
	private String ecptCode;
	
	/**
	 */
	@Column(name = "ECPT_MESSAGE", nullable = false, length = 200)
	private String ecptMessage;
	
	/**
	 */
	@Column(name = "CREATE_TIME", nullable = false)
	private Date createTime;

	public ExceptionLog() {
	}

	public ExceptionLog(Long id, FwAccount fwAccount,
			FwSource fwSource, String ecptModule, String ecptCode,
			String ecptMessage, Date createTime) {
		this.id = id;
		this.fwAccount = fwAccount;
		this.fwSource = fwSource;
		this.ecptModule = ecptModule;
		this.ecptCode = ecptCode;
		this.ecptMessage = ecptMessage;
		this.createTime = createTime;
	}

	/**  
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**  
	 */
	public FwAccount getFwAccount() {
		return this.fwAccount;
	}

	/**
	 */
	public void setFwAccount(FwAccount fwAccount) {
		this.fwAccount = fwAccount;
	}

	/**  
	 */
	public FwSource getFwSource() {
		return this.fwSource;
	}

	/**
	 */
	public void setFwSource(FwSource fwSource) {
		this.fwSource = fwSource;
	}

	/**  
	 */
	public String getEcptModule() {
		return this.ecptModule;
	}

	/**
	 */
	public void setEcptModule(String ecptModule) {
		this.ecptModule = ecptModule;
	}

	/**  
	 */
	public String getEcptMessage() {
		return this.ecptMessage;
	}

	/**
	 */
	public void setEcptMessage(String ecptMessage) {
		this.ecptMessage = ecptMessage;
	}

	/**  
	 */
	public Serializable getCreateTime() {
		return this.createTime;
	}

	/**
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getEcptCode() {
		return ecptCode;
	}

	public void setEcptCode(String ecptCode) {
		this.ecptCode = ecptCode;
	}

}
