package oracle.model;

// Generated 2016-1-14 14:54:08 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.huatek.frame.core.model.BaseEntity;

/**
 * FwActionLog generated by hbm2java
 */
@Entity
@Table(name = "FW_ACTION_LOG", schema = "")
public class FwActionLog extends BaseEntity {

	
	/**
	 */
	@Id
	@Column(name = "act_log_id", unique = true, nullable = false)
	@SequenceGenerator(name="seq_fali", sequenceName="S_FW_ACTION_LOG_ID")
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="seq_fali")
	private Long id;
	
	/**
	 * 用户ID.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCT_ID", nullable = false)
	private FwAccount fwAccount;
	
	/**
	 * 操作ID.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACTION_ID", nullable = false)
	private FwSource fwSource;
	
	/**
	 * 操作时间.
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "ACTION_TIME", nullable = false)
	private Date actionTime;
	
	/**
	 * 客户端IP.
	 */
	@Column(name = "CLIENT_IP", length = 40)
	private String clientIp;
	
	/**
	 * 端口.
	 */
	@Column(name = "CLIENT_PORT")
	private int clientPort;
	@Column(name = "TENANT_ID")
	private Long tenantId;
	public FwActionLog() {
	}

	public FwActionLog(Long id, FwAccount fwAccount,
			FwSource fwSource, Date actionTime) {
		this.id = id;
		this.fwAccount = fwAccount;
		this.fwSource = fwSource;
		this.actionTime = actionTime;
	}

	public FwActionLog(Long id, FwAccount fwAccount,
			FwSource fwSource, Date actionTime, String clientIp,
			int clientPort) {
		this.id = id;
		this.fwAccount = fwAccount;
		this.fwSource = fwSource;
		this.actionTime = actionTime;
		this.clientIp = clientIp;
		this.clientPort = clientPort;
	}

	/**  
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**  
	 * 取得 用户ID.
	 */
	public FwAccount getFwAccount() {
		return this.fwAccount;
	}

	/**
	 * 设置 用户ID.
	 */
	public void setFwAccount(FwAccount fwAccount) {
		this.fwAccount = fwAccount;
	}

	/**  
	 * 取得 操作ID.
	 */
	public FwSource getFwSource() {
		return this.fwSource;
	}

	/**
	 * 设置 操作ID.
	 */
	public void setFwSource(FwSource fwSource) {
		this.fwSource = fwSource;
	}

	/**  
	 * 取得 操作时间.
	 */
	public Date getActionTime() {
		return this.actionTime;
	}

	/**
	 * 设置 操作时间.
	 */
	public void setActionTime(Date actionTime) {
		this.actionTime = actionTime;
	}

	/**  
	 * 取得 客户端IP.
	 */
	public String getClientIp() {
		return this.clientIp;
	}

	/**
	 * 设置 客户端IP.
	 */
	public void setClientIp(String clientIp) {
		this.clientIp = clientIp;
	}

	/**  
	 * 取得 端口.
	 */
	public int getClientPort() {
		return this.clientPort;
	}

	/**
	 * 设置 端口.
	 */
	public void setClientPort(int clientPort) {
		this.clientPort = clientPort;
	}

	public Long getTenantId() {
		return tenantId;
	}

	public void setTenantId(Long tenantId) {
		this.tenantId = tenantId;
	}

}
